#!/bin/bash

files_changed=$(git status)

for file in $files_changed
do
	if [[ $file == *.go ]]
	then
		cp $file /tmp
		go fmt /tmp/$file
		if [[ $(diff $file /tmp/$file) != "" ]]
		then
			echo "The changed file are not in the expected go format"
			exit 1
		fi
	fi
done


