#!/bin/bash

cd ../../

files=$(ls)

go fmt

format_files() {
	cd $1
	go fmt
	files=$(ls)
	for file in $files
	do
		if [[ -d "$file" ]]
		then
			format_files $file
		fi
	done
}

for file in $files
do
	if [[ -d "$file" ]]
	then
		format_files $file
	fi
done

exit $?
